import Head from "next/head";
import Image from "next/image";
import { useGlobalContext } from "../components/context";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import ThumbnailCard from "./thumbnailcard";

export default function Home({ results }) {
  const { isDetailOpen, currentId } = useGlobalContext();
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isDetailOpen && (
        <div className="sticky top-0 z-50">
          <ThumbnailCard results={results} currentid={currentId} />
        </div>
      )}
      {/* Header */}
      <Header />
      {/* Nav */}
      <Nav />
      {/* Results */}
      <Results results={results} />
    </div>
  );
}

// User entra na pagina
// Renderizo server side fazendo um fetch para a API
// Por exemplo fetchTrending.
// Depois de eu fazer esse fetch eu tenho que retornar o data object
// Para o Result component dar render nessa data

// Daí eu clico por em outro botão, e ai faço o mesmo rolê dali de cima

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );

  const data = await request.json();

  return {
    props: {
      results: data.results,
    },
  };
}
